name: Deployment workflow
on:
  push:
    branches: [ master ]

  jobs:
    job_one:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - name: testing ssh connection
          uses: